name: Continuous integration
on: [push, pull_request]
jobs:
  ci:
    name: Validate
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        username: stephanmisc
        password: ${{ secrets.DOCKER_PASSWORD }}
      if: github.event_name == 'push'
    - uses: stepchowfun/toast/.github/actions/toast@main
      with:
        tasks: verify lint
        docker_repo: stephanmisc/toast
        write_remote_cache: ${{ github.event_name == 'push' }}
